name: sentiment-analysis-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pip:
      - torch
      - torchvision
      - torchaudio
      - datasets
      - transformers
      - scikit-learn
      - matplotlib
      - numpy
      - pandas
      - tqdm
